// Real MSIPL product catalog (existing site data — not invented).
// Shared by /products (Shop Online) and /brands (Brand & Products) so both
// pages stay in sync with a single source of product data.

export const categories = [
  "All Products",
  "Detergent Cakes & Bars",
  "Washing Powders",
  "Dishwash",
  "Beauty Soap",
  "Floor & Toilet Cleaners",
  "Fabric Conditioner",
  "Pouches & Packs",
  "Cleaning Aids",
];

export interface Product {
  id: number;
  name: string;
  category: string;
  description: string;
  price: number;
  rating: number;
  reviews: number;
  image: string;
  bestseller: boolean;
  new: boolean;
  extent?: string[];
}

export const allProducts: Product[] = [
  {
    id: 1,
    name: "Shashi Pink M-Lore Detergent Cake",
    category: "Detergent Cakes & Bars",
    description: "Detergent cake for daily washing 150G & 60 PCS",
    price: 15,
    rating: 4.5,
    reviews: 120,
    image: "/images/SHASHI PIKK DEETERGENT CAKE.webp",
    bestseller: false,
    new: false,
  },
  {
    id: 2,
    name: "Shashi Pink Pouch",
    category: "Pouches & Packs",
    description: "Compact detergent pouch",
    price: 10,
    rating: 4.4,
    reviews: 95,
    image: "/images/Shashi Pink Pouch.webp",
    bestseller: false,
    new: false,
    extent: ['(125g)', '(150g)', '(200g)']
  },
  {
    id: 3,
    name: "Shashi Pink Bullet Set",
    category: "Detergent Cakes & Bars",
    description: "Bullet detergent cake 1 SET ,6 PCS",
    price: 180,
    rating: 4.6,
    reviews: 85,
    image: "/images/SHASHI PINK BULLET.webp",
    bestseller: false,
    new: false,
  },
  {
    id: 4,
    name: "Shashi Pink Bullet Pouch",
    category: "Pouches & Packs",
    description: "Bullet detergent cake 250G 60 PCS",
    price: 30,
    rating: 4.6,
    reviews: 85,
    image: "/images/Shashi Pink Pouch.webp",
    bestseller: false,
    new: false,
  },
  {
    id: 5,
    name: "Shashi Arya Blue Detergent Cake",
    category: "Detergent Cakes & Bars",
    description: "Arya blue detergent cake",
    price: 26,
    rating: 4.6,
    reviews: 130,
    image: "/images/SHASHI ARYA BLUE.webp",
    bestseller: false,
    new: false,
    extent: ['(250g)', '(300g)']
  },
  {
    id: 9,
    name: "Shashi Pink & Blue Washing Powder",
    category: "Washing Powders",
    description: "Dual colour washing powder",
    price: 90,
    rating: 4.7,
    reviews: 155,
    image: "/images/SHASHI PINK & BLUE WASHING POWDE 1kg-MRP-100.webp",
    bestseller: false,
    new: false,
  },
  {
    id: 10,
    name: "Shashi Hi-Clean Washing Powder",
    category: "Washing Powders",
    description: "Hi-clean detergent powder",
    price: 10,
    rating: 4.5,
    reviews: 140,
    image: "/images/SHASHI CLEAN WASHING POWDER.webp",
    bestseller: false,
    new: false,
  },
  {
    id: 12,
    name: "Shashi Triple Action Detergent Powder",
    category: "Washing Powders",
    description: "Triple action detergent powder",
    price: 99,
    rating: 4.8,
    reviews: 210,
    image: "/images/SHASHI TRIPLE ACTION.webp",
    bestseller: false,
    new: false,
    extent: ['(500g)', '(1kg)', '(3+1kg)']
  },
  {
    id: 14,
    name: "Shashi Bheema Phenyl",
    category: "Floor & Toilet Cleaners",
    description: "Phenyl floor cleaner",
    price: 90,
    rating: 4.6,
    reviews: 160,
    image: "/images/SHASHI BHEEMAA PHYNYL.webp",
    bestseller: false,
    new: false,
  },
  {
    id: 16,
    name: "Mr Win Washing Powder",
    category: "Washing Powders",
    description: "Budget washing powder",
    price: 10,
    rating: 4.3,
    reviews: 120,
    image: "/images/Mr_WIN_WASHING_POWDER.webp",
    bestseller: false,
    new: false,
  },
  {
    id: 17,
    name: "Shashi Gramflour Beauty Soap",
    category: "Beauty Soap",
    description: "Jar packed beauty soap",
    price: 150,
    rating: 4.7,
    reviews: 140,
    image: "/images/Shashi Gramflour Beauty Soap.webp",
    bestseller: false,
    new: false,
    extent: ['(4pc Jar)', '(6pc Jar)']
  },
  {
    id: 18,
    name: "Shashi Papaya Beauty Soap",
    category: "Beauty Soap",
    description: "Papaya beauty soap jar",
    price: 230,
    rating: 4.8,
    reviews: 170,
    image: "/images/SHASHI PAPAYA BEAUTY SOAP (4PC JAR).webp",
    bestseller: false,
    new: false,
    extent: ['(4pc Jar)', '(6pc Jar)']
  },
  {
    id: 19,
    name: "Shashi Fabric Conditioner",
    category: "Fabric Conditioner",
    description: "Fabric softener",
    price: 4,
    rating: 4.4,
    reviews: 110,
    image: "/images/Shashi Fabric Conditioner.webp",
    bestseller: false,
    new: false,
  },
  {
    id: 20,
    name: "Savaal Oxydol Dishwash Gel",
    category: "Dishwash",
    description: "Dishwash gel",
    price: 150,
    rating: 4.6,
    reviews: 145,
    image: "/images/SAVAAL_OXYDOL_DISHWASH_GEL.webp",
    bestseller: false,
    new: false,
  },
  {
    id: 22,
    name: "Savaal Captain Floor Cleaner",
    category: "Floor Cleaner",
    description: "Floor cleaning liquid",
    price: 199,
    rating: 4.7,
    reviews: 160,
    image: "/images/SAVAAL_CAPTAIN_FLOOR_CLEANER.webp",
    bestseller: false,
    new: false,
  },
  {
    id: 23,
    name: "Shashi Sandal Beauty Soap",
    category: "Beauty Soap",
    description: "Sandal fragrance soap",
    price: 45,
    rating: 4.8,
    reviews: 180,
    image: "/images/SHASHI SANDAL BEAUTY SOAP.webp",
    bestseller: false,
    new: false,
  },
  {
    id: 24,
    name: "Shashi Washing Powder",
    category: "Washing Powders",
    description: "General purpose washing powder",
    price: 55,
    rating: 4.5,
    reviews: 120,
    image: "/images/SHASHI WASHING POWDER.webp",
    bestseller: false,
    new: false
  },
  {
    id: 25,
    name: "Shashi Hi-Clean Washing Powder",
    category: "Washing Powders",
    description: "Hi-clean detergent powder",
    price: 60,
    rating: 4.6,
    reviews: 140,
    image: "/images/SHASHI CLEAN WASHING POWDER.webp",
    bestseller: true,
    new: false
  },
  {
    id: 27,
    name: "Mr Win Washing Powder",
    category: "Washing Powders",
    description: "Economical washing powder",
    price: 50,
    rating: 4.3,
    reviews: 90,
    image: "/images/Mr_WIN_WASHING_POWDER.webp",
    bestseller: false,
    new: false
  },
  {
    id: 28,
    name: "Savaal Gold Washing Powder",
    category: "Washing Powders",
    description: "Premium washing powder",
    price: 100,
    rating: 4.5,
    reviews: 110,
    image: "/images/SAVAAL_GOLD_WASHING_POWDER.webp",
    bestseller: false,
    new: false
  },
  {
    id: 29,
    name: "Savaal 999 Washing Powder",
    category: "Washing Powders",
    description: "High performance detergent",
    price: 60,
    rating: 4.6,
    reviews: 130,
    image: "/images/SHASHI WASHING POWDER.webp",
    bestseller: true,
    new: false
  },
  {
    id: 30,
    name: "Savaal Blue Pouch",
    category: "Washing Powders",
    description: "Compact washing powder pouch",
    price: 10,
    rating: 4.4,
    reviews: 80,
    image: "/images/SAVAAL BLUE POUCH 100g-MP-10.webp",
    bestseller: false,
    new: false
  },
  {
    id: 32,
    name: "Shashi Blue Pouch",
    category: "Detergent Cakes & Bars",
    description: "Blue detergent pouch",
    price: 10,
    rating: 4.5,
    reviews: 145,
    image: "/images/SHASHI_BLUE_POUCH.webp",
    bestseller: true,
    new: false
  },
  {
    id: 33,
    name: "Shashi Pink Detergent Cake",
    category: "Detergent Cakes & Bars",
    description: "Classic pink detergent cake",
    price: 12,
    rating: 4.6,
    reviews: 210,
    image: "/images/SHASHI PIKK DEETERGENT CAKE.webp",
    bestseller: true,
    new: false
  },
  {
    id: 34,
    name: "Shashi Anti Bacterial Detergent Cake",
    category: "Detergent Cakes & Bars",
    description: "Anti bacterial detergent cake",
    price: 25,
    rating: 4.7,
    reviews: 190,
    image: "/images/SHASHI ANTIBACTERIAL DETERGENT CAKE.webp",
    bestseller: false,
    new: false
  },
  {
    id: 35,
    name: "Mr Bheem Detergent Cake",
    category: "Detergent Cakes & Bars",
    description: "Heavy duty detergent cake",
    price: 15,
    rating: 4.4,
    reviews: 160,
    image: "/images/MBHEEM DETERGENT CAKE.webp",
    bestseller: false,
    new: false
  },
  {
    id: 36,
    name: "Mr Bheem Detergent Powder",
    category: "Detergent Powder",
    description: "Heavy duty detergent powder",
    price: 15,
    rating: 4.4,
    reviews: 160,
    image: "/images/Mr Bheem Detergent Powder.webp",
    bestseller: false,
    new: false
  },
  {
    id: 37,
    name: "Savaal White Pouch",
    category: "Detergent Cakes & Bars",
    description: "White detergent pouch",
    price: 10,
    rating: 4.3,
    reviews: 140,
    image: "/images/SAVAAL WHITE POUCH.webp",
    bestseller: false,
    new: false
  },
  {
    id: 38,
    name: "Savaal Max Blue Detergent Cake",
    category: "Detergent Cakes & Bars",
    description: "Blue detergent cake",
    price: 10,
    rating: 4.5,
    reviews: 170,
    image: "/images/SAVAAL_MAX_BLUE_DETERGENT_CAKE.webp",
    bestseller: true,
    new: false
  },
  {
    id: 39,
    name: "Savaal White Gold Detergent Cake",
    category: "Detergent Cakes & Bars",
    description: "Premium detergent cake",
    price: 25,
    rating: 4.6,
    reviews: 200,
    image: "/images/SAVAAL WHITE GOLD DETINGENT CAKE.webp",
    bestseller: true,
    new: false
  },
  {
    id: 40,
    name: "Savaal More Bright Detergent Cake",
    category: "Detergent Cakes & Bars",
    description: "Extra bright detergent cake",
    price: 20,
    rating: 4.4,
    reviews: 155,
    image: "/images/SAVAAL MORE BRIGHT DETERGENT CAKE.webp",
    bestseller: false,
    new: false
  },
  {
    id: 41,
    name: "Savaal Max White Detergent Cake",
    category: "Detergent Cakes & Bars",
    description: "White detergent cake",
    price: 10,
    rating: 4.5,
    reviews: 165,
    image: "/images/SAVAAL_MAX_WHITE_DETERGENT_CAKE.webp",
    bestseller: false,
    new: false
  },
  {
    id: 42,
    name: "Savaal White Detergent Cake",
    category: "Detergent Cakes & Bars",
    description: "Standard white detergent cake",
    price: 12,
    rating: 4.4,
    reviews: 150,
    image: "/images/SAVAAL_WHITE_DETERGENT_CAKE.webp",
    bestseller: false,
    new: false
  },
  {
    id: 43,
    name: "Savaal Oxydol Dishwash Bar",
    category: "Dishwash",
    description: "Oxydol dishwash bar",
    price: 10,
    rating: 4.6,
    reviews: 180,
    image: "/images/SAVAAL OXYEOL DISHWASH BAR.webp",
    bestseller: true,
    new: false
  },
  {
    id: 44,
    name: "Savaal Oxydol Dishwash Bar Round",
    category: "Dishwash",
    description: "Round dishwash bar",
    price: 25,
    rating: 4.7,
    reviews: 200,
    image: "/images/SAVAAL OXYDOL DISHWASH BAR .webp",
    bestseller: true,
    new: false
  },
  {
    id: 45,
    name: "Savaal Oxydol Dishwash Gel",
    category: "Dishwash Gel",
    description: "Dishwash gel",
    price: 105,
    rating: 4.7,
    reviews: 170,
    image: "/images/SAVAAL_OXYDOL_DISHWASH_GEL.webp",
    bestseller: true,
    new: false
  },
  {
    id: 46,
    name: "Shashi Arya Dishwash Bar",
    category: "Dishwash",
    description: "Arya dishwash bar",
    price: 10,
    rating: 4.5,
    reviews: 160,
    image: "/images/SHASHI ARYA DISHWASHI BAR.webp",
    bestseller: false,
    new: false
  },
  {
    id: 47,
    name: "Shashi Arya Dishwash Bar Round",
    category: "Dishwash",
    description: "Arya round dishwash bar",
    price: 25,
    rating: 4.6,
    reviews: 175,
    image: "/images/SHASHI ARYA DISHWASH BAR ROUND.webp",
    bestseller: false,
    new: false
  },
  {
    id: 48,
    name: "Shashi Scouring Powder",
    category: "Cleaning Aids",
    description: "Scouring powder",
    price: 10,
    rating: 4.4,
    reviews: 140,
    image: "/images/SHASHI SCOURING POWDER .webp",
    bestseller: false,
    new: false
  },
  {
    id: 49,
    name: "Shashi Sandal Beauty Soap",
    category: "Beauty Soap",
    description: "Sandal soap",
    price: 30,
    rating: 4.8,
    reviews: 240,
    image: "/images/SHASHI SANDAL BEAUTY SOAP.webp",
    bestseller: true,
    new: false
  },
  {
    id: 50,
    name: "Shashi Neem & Tulasi Beauty Soap",
    category: "Beauty Soap",
    description: "Herbal soap",
    price: 30,
    rating: 4.7,
    reviews: 220,
    image: "/images/SHASHI NEEM A TULASI BEAUTY SOAR.webp",
    bestseller: false,
    new: false
  },
  {
    id: 51,
    name: "Shashi Gram Flour Beauty Soap",
    category: "Beauty Soap",
    description: "Gram flour soap",
    price: 120,
    rating: 4.9,
    reviews: 300,
    image: "/images/SHASHI GRAM POWDER BEAUTY SOAP.webp",
    bestseller: true,
    new: false
  },
  {
    id: 52,
    name: "Shashi Bheema Phenyl",
    category: "Floor & Toilet Cleaners",
    description: "Phenyl floor cleaner",
    price: 70,
    rating: 4.6,
    reviews: 180,
    image: "/images/SHASHI BHEEMAA PHYNYL.webp",
    bestseller: false,
    new: false
  },
  {
    id: 53,
    name: "Savaal Extra Act Phenyl",
    category: "Floor & Toilet Cleaners",
    description: "Extra active phenyl",
    price: 70,
    rating: 4.6,
    reviews: 170,
    image: "/images/SAVAAL EXTRAA ACT PHYS.webp",
    bestseller: false,
    new: false
  },
  {
    id: 54,
    name: "Shashi Scrubber",
    category: "Cleaning Aids",
    description: "Steel scrubber",
    price: 15,
    rating: 4.4,
    reviews: 160,
    image: "/images/SHASHI SCRUBBER.webp",
    bestseller: false,
    new: false
  },
  {
    id: 64,
    name: "Savaal Scrubber",
    category: "Cleaning Aids",
    description: "Steel scrubber",
    price: 15,
    rating: 4.4,
    reviews: 150,
    image: "/images/SAVAAL SCRUBBER.webp",
    bestseller: false,
    new: false
  },
  {
    id: 55,
    name: "Savaal Captain Floor Cleaner",
    category: "Floor & Toilet Cleaners",
    description: "Floor cleaning liquid",
    price: 93,
    rating: 4.7,
    reviews: 200,
    image: "/images/SAVAAL_CAPTAIN_FLOOR_CLEANER.webp",
    bestseller: true,
    new: false
  },
  {
    id: 56,
    name: "Savaal Captain Toilet Cleaner",
    category: "Floor & Toilet Cleaners",
    description: "Toilet cleaning liquid",
    price: 90,
    rating: 4.6,
    reviews: 190,
    image: "/images/SAVAAL CAPTAIN TOILET CLEANE.webp",
    bestseller: true,
    new: false
  },
  {
    id: 57,
    name: "Shashi Matic Liquid Detergent",
    category: "Fabric Conditioner",
    description: "Liquid detergent for machines",
    price: 220,
    rating: 4.6,
    reviews: 160,
    image: "/images/SHASHI MATIC.webp",
    bestseller: true,
    new: false
  },
  {
    id: 58,
    name: "Shashi Pink Detergent Cake",
    category: "Detergent Cakes & Bars",
    description: "Pink detergent cake",
    price: 20,
    rating: 4.5,
    reviews: 145,
    image: "/images/SHASHI PIKK DEETERGENT CAKE.webp",
    bestseller: false,
    new: false
  }
];

export type BrandKey = "shashi" | "savaal" | "shashi-plus";

export function brandOf(product: Product): BrandKey | "other" {
  const name = product.name.toLowerCase();
  if (name.startsWith("shashi")) return "shashi";
  if (name.startsWith("savaal")) return "savaal";
  return "other";
}

export function productsByBrand(brand: BrandKey) {
  return allProducts.filter((p) => brandOf(p) === brand);
}
